# Generated by Django 4.1.3 on 2023-02-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_general", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(null=True, upload_to="images/")),
            ],
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
