# Generated by Django 4.1.3 on 2023-02-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_general", "0002_image2_alter_image_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="images")),
            ],
        ),
    ]
