# Generated by Django 4.1.3 on 2023-02-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_general", "0003_uploadimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image2",
        ),
        migrations.DeleteModel(
            name="UploadImage",
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
