# Generated by Django 4.1.3 on 2023-02-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_general", "0004_delete_image2_delete_uploadimage_alter_image_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="noisemap_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.CharField(max_length=200, verbose_name="x")),
                ("y", models.CharField(max_length=200, verbose_name="y")),
                ("z", models.CharField(max_length=200, verbose_name="z")),
            ],
        ),
    ]
