# Generated by Django 4.1.3 on 2023-02-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_general", "0005_noisemap_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noisemap_data",
            name="x",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="noisemap_data",
            name="y",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="noisemap_data",
            name="z",
            field=models.CharField(max_length=200),
        ),
    ]
