# Generated by Django 4.1.3 on 2023-02-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_general", "0007_noisemap_delete_noisemap_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noisemap",
            name="x",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="noisemap",
            name="y",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="noisemap",
            name="z",
            field=models.IntegerField(),
        ),
    ]
