# Generated by Django 4.1.3 on 2023-02-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_general", "0008_alter_noisemap_x_alter_noisemap_y_alter_noisemap_z"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noisemap",
            name="z",
            field=models.FloatField(),
        ),
    ]
